javascript_compressor:  closure
css_compressor:         sass
template_function:      DocumentCloud._.template
gzip_assets:            off
embed_assets:           off
rewrite_relative_paths: off

javascripts:
  page_embed:
    # Modernizr sniffs svg/touch and provides our html5shim
    - src/js/vendor/modernizr.custom.js
    - src/js/vendor/jquery/dist/jquery.js
    # jQuery.XDomainRequest is for IE8/9
    - src/js/vendor/jQuery-ajaxTransport-XDomainRequest/jQuery.XDomainRequest.js
    - src/js/vendor/underscore/underscore.js
    - src/js/vendor/backbone/backbone.js
    - src/js/util/logger.js
    - src/js/util/setup.js
    - src/js/util/toolbelt.js
    - src/js/models/*.js
    - src/js/views/*.js
    - src/js/loaders/page.js
    - src/templates/*.jst

  enhance:
    - src/js/util/logger.js
    - src/js/util/penny.js
    - src/js/util/toolbelt.js
    - src/js/enhance.js

stylesheets:
  page_embed:
    - src/css/vendor/fontello/fontello-embedded.css
    - src/css/vendor/fontello/animation.css
    - src/css/*.css
    - src/css/*.scss
